### ISSUE TITLE
Cataclysm

### ISSUE THREAD

**Issue by dkcas11** [Byloth/cmangos-docker#17]
Any chance you could add support for Cataclysm? 🤞

**Comment by Byloth** [comment]
Hey, @dkcas11!  
Nice to meet you! 🙃

First of all...
Thanks for your interest in this project.

Well...  
To be honest, this project is just a _containerization_ of the [CMaNGOS](https://github.com/cmangos) original project that uses [Docker](https://www.docker.com/) to make it easier and more convenient for everyone to use.  
For this reason I don't directly develop the WoW server itself but I just use the one developed by another team.

The CMaNGOS team -actually- doesn't support Cataclysm, so there's no server application to containerize for this project.

Sorry about that. 🥺

---

Anyway...
If you're wondering why they decided not to support Cataclysm, I've found a short discussion about this topic on the official [CMaNGOS Discord server](https://discord.gg/Dgzerzb)...

![image](https://github.com/Byloth/cmangos-docker/assets/14953974/1632ec28-2582-48b5-9519-28e8c65a4991)

**Comment by dkcas11** [comment]
@Byloth Thanks for looking into the Discord about the absense of Cata. I completely overlooked the fact that this is CManGOS and not ManGOS, so I was sure Cataclysm was there, i.e. Mangos-Three 🤦‍♂️ 

I looked a bit into the project here to see how things were setup and if I could add a container for Cataclysm myself but frankly I'm just not too skilled with that _yet_. 

Out of curiosity do you know how much the two projects differ when it comes to containerization?

**Comment by Byloth** [comment]
No problem, @dkcas11! 🙃

Well... Good question! 🤔  
I quickly read the MaNGOS [Installation documentation](https://www.getmangos.eu/wiki/documentation/installation-guides/guideslinux/installing-mangos-on-ubuntu-server-2204-r40014/) and -apart from the order of the steps- I've found many similarities...

Now...
Is it easy to containerize a MaNGOS server application starting from a CMaNGOS one? Well... It could be.

The steps in the documentation are pretty clear but you need to know how containerization works in order to understand which of these steps need to be written inside a `Dockerfile` file and which don't...
For example, all database data related steps don't have to be included in a `Dockerfile`.

---

More generally, this type of containerization could be a perfect project to delve deeper into Docker and learn many new things... Or, at least, CMaNGOS Docker was that for me. 😉
