### ISSUE TITLE
Permission denied on extractor for Asset Data. (Possibly missing Execution bit?)

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Byloth/cmangos-docker#24]
# docker run -it --rm \
>            --volume "cmangos_mangosd_data:/home/mangos/data" \
>            --volume "/opt/var/public/Windows/Games/WoW/World of Warcraft/:/home/mangos/wow-client" \
>     \
>     ghcr.io/byloth/cmangos/wotlk/builder:latest extract
Unable to find image 'ghcr.io/byloth/cmangos/wotlk/builder:latest' locally
latest: Pulling from byloth/cmangos/wotlk/builder
32b824d45c61: Already exists 
36c44df2edb2: Pull complete 
1da489b7e19e: Pull complete 
7feee0b8ae92: Pull complete 
1cfbaf893b59: Pull complete 
4f4fb700ef54: Pull complete 
f1b8f1748a0d: Pull complete 
a6626528bb51: Pull complete 
Digest: sha256:171835a7ec97f66b777ea59b4c5dff201b6d6ad7eca0bfdd069cb57bd1acf570
Status: Downloaded newer image for ghcr.io/byloth/cmangos/wotlk/builder:latest
/entrypoint.sh: line 76: ./ExtractResources.sh: Permission denied

**Comment by Zombie-Ryushu** [comment]
cmangos-mariadb-1  | 2024-10-01 19:22:55 6 [Warning] Access denied for user 'mangos'@'172.20.0.3' (using password: YES)
cmangos-mangosd-1  | Could not connect to MySQL database at mariadb: Access denied for user 'mangos'@'172.20.0.3' (using password: YES)
c

**Comment by Zombie-Ryushu** [comment]
I suspect some database population is not taking place.

**Comment by Byloth** [comment]
Hi, @Zombie-Ryushu!
Thanks for reporting!

I suspect that something in the [CMaNGOS repository](https://github.com/cmangos/mangos-wotlk) may have changed.

I'll look into it and get back to you soon! 🙃

**Comment by Byloth** [comment]
Hi, @Zombie-Ryushu!

I tried to investigate your first problem, the one about to the possible missing execution bit.  
The file executed by the `/entrypoint.sh` on line 76 comes from the official [CMaNGOS repository](https://github.com/cmangos/mangos-wotlk) and [has been untouched](https://github.com/cmangos/mangos-wotlk/commits/f5c57fb54be7ce17dbab79d27c1b340640ab98e0/contrib/extractor_scripts/ExtractResources.sh) for a year, now.

And it's -indeed- executable.

Here's the output of my tests, using your the same image:

![image](https://github.com/user-attachments/assets/56fe34be-19a9-4698-b334-2492a1984e8e)

---

Your problem is quite strange, to be honest...  
But I'm starting to think that all those problems may be related to a configuration problem of yours more than some malfunctions in this project.

**BUT...**  
I'll be heppy to help, if I can!

If you'd prefer to keep this project private, write me an [e-mail](https://github.com/Byloth) describing all your project's details or sharing your fork with me so I can dig deeper into it and investigate directly on your project.

This would also help me understand how you're handling the Docker networking between containers; it seems like there's some sort of misconfiguration and that's why they're unable to communicate.

Thanks!

**Comment by Zombie-Ryushu** [comment]
I managed to resolve the execution bit issue by just flagging everything executable. What I am having issue with now, is generating the database tables. I checked the MariaDB instance. I have no  tables or users for Mangos in MariaDB, this tells me I am not doing the needed action to create the databases.

**Comment by Zombie-Ryushu** [comment]
In short, what I need now is the command to generate the MariaDB Tables, extraction of assets was successful.

**Comment by Byloth** [comment]
Oh, ok... Great! 😉

Yeah! That's the correct state where you should find your MariaDB instance on the first run...
So, from here on, you can find your next steps: [Getting started - Database initialization](https://github.com/Byloth/cmangos-docker/wiki/getting-started#databases-initialization)

Please note that -on the Wiki- there are some sections that can be expanded by clicking on them, depending on your environment... Here -for example- if you're using Unix / Unix-like OS:

![image](https://github.com/user-attachments/assets/6e3d5014-6f57-4df1-9185-337f6517b863)

The `init-db` command will configure your DB for the first server run! 😉

**Comment by Zombie-Ryushu** [comment]
Thank you!
