### ISSUE TITLE
docs: Missing update for `reamlist` table in Wiki

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Byloth/cmangos-docker#25]
So I have a client successfully connecting, databases provisioned and everything. yet when I try and connect a client, I get stuck on Realm selection. Any attempt to initiate connection to a realm results in being booted back to the realm selection screen.

**Comment by Zombie-Ryushu** [comment]
Note: this is a Remote Client, another Linux host running the Client in Wine.

**Comment by Zombie-Ryushu** [comment]
got  it working!

I had to docker attach it to another network and change a line in the realm table.

**Comment by Byloth** [comment]
Hi, @Zombie-Ryushu!  
Thanks for reporting!

Indeed!
You found a missing piece on the documentation... My bad! 🥺

I need to add this step to the Wiki...
Here's the missing step on the official CMaNGOS wiki: https://github.com/cmangos/issues/wiki/Installation-Instructions#optional-update-realmdrealmlist

**Comment by Byloth** [comment]
I really appreciated all your effort in this project!  
All your reports have helped a lot to make it even more user friendly (and that's awesome)! 🤩

Since you said you're using a complex Docker configuration, could you share it with me?  
It might help to write and imrpove some of the unfinished Wiki pages, like "[Server Configuration](https://github.com/Byloth/cmangos-docker/wiki/server-configuration)", "[Customization](https://github.com/Byloth/cmangos-docker/wiki/customization)" and maybe even "[Use in Production](https://github.com/Byloth/cmangos-docker/wiki/use-in-production)"!

Thanks again for your interest and your help!  
Really appreciated! 🥹

---

I will close this Issue as soon as I've written the missing part about the `realmlist` table configuration.

**Comment by Zombie-Ryushu** [comment]
Do you know anything about Character import from earlier instances of Mangos?

**Comment by Byloth** [comment]
CMaNGOS Docker doesn't offer any in that sense...
However, the `builder` container includes the `mysql` client.

So -I imagine- it should be enough to use it as normal.

**e.g.**
```sh
./builder/run.sh mysql -u<user> -p <database> < path/to/previous/characters.sql
```

**Comment by Zombie-Ryushu** [comment]
Thats what I tried to do with mixed results.

**Comment by Byloth** [comment]
Just for anyone who will bumps into this issue in the future...  
Here's the missing part of the documentation about [Configuring the `realmlist` table](https://github.com/Byloth/cmangos-docker/wiki/Getting-Started#configure-the-realmlist-table).
