### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by mserajnik** [Byloth/cmangos-docker#8]
Hello,

first of all, thanks for your work!

I have recently put together a [Docker setup for VMaNGOS](https://github.com/mserajnik/vmangos-deploy)<sup>1</sup> ; I am quite happy with it, but it's certainly a lot less impressive than your CMaNGOS setup here.

I've since then looked into maybe also creating a Docker setup for CMaNGOS (TBC in particular, since that what interests me personally) and stumbled upon your project here.

From what I can tell, there's definitely no need for me to start a new project, but I've noticed two things in particular:

1. The documentation seems to be unfinished/not correct in some places; e.g, the README tells you to run `./build.sh --target all` when that seems unnecessary when using the prebuilt images (and is also not mentioned in the [wiki](https://github.com/Byloth/cmangos-docker/wiki/Getting-Started)). I there probably isn't too much information missing, but it seems like it needs to be cleaned up a bit.
2. The update process is not entirely clear; it seems like you can't do a proper update in some situations without manual actions as you stated in https://github.com/Byloth/cmangos-docker/issues/4

Now, I've noticed that you haven't committed to this project in January and was wondering if these are still things you want to sort out (and are still interested in working on the project in general)? I'd be happy to help if I can in some way.

<sup>1</sup><sup><sub>: Actually, it's my second setup for VMaNGOS, although the first one was basically just a simplification (and slight expansion) of existing work and didn't feature any prebuilt images.</sub></sup>

**Comment by Byloth** [comment]
Hello!
Thanks for your kind words and your interest into this project! 🥹

So...  
The project is currently quite up to date; I haven't tried it in a while but I don't expect any major flaws... It should work as expected.

The only thing that unpleasantly comes to my mind, is that the GitHub Actions workflow needs to be updated in order to build images even using a daily tag.  
[There are](https://github.com/Byloth/cmangos-docker/pkgs/container/cmangos%2Ftbc/versions) so many untagged images because when I designed it I only planned to use 3 different tags: `latest`, the branch's name the build comes from (ideally `master`) and the commit's hash the build comes from.

Since it's been a long time since the last commit, I started to notice that it would be better to add a new build tag related to the day it was built.  
You know... It makes sense to me; a user should be able to pull a specific image built on a specific date.

---

Apart from this...
As you also noted, the `README.md` is extremely outdated (it comes from when there were no images built with GitHub Actions yet and you had to build images yourself) and the documentation is incomplete (I stopped [here](https://github.com/Byloth/cmangos-docker/wiki/Getting-Started#using-the-cmangos-console) from writing).

And also...
Since the script that comes from the [original CMaNGOS project](https://github.com/cmangos/tbc-db/) isn't actually "friendly" with non-interactive use, you currently have to `docker exec` into the container in order to run the database `CoreUpdate` command.

A while ago, I talked with the core team on the CMaNGOS Discord server and they told me that -right now- they're not confident in merge [my PR](https://github.com/cmangos/tbc-db/pull/1112) because the new option might cause confusion with the current user base that use CMaNGOS as it is, they do not actually understand why the option should be added and that they are reluctant because they absolutely don't want this to lead to some strange and uncontrolled self-updating behaviour (which -of course- it isn't).  
For this reason, I started writing the wiki, in order to describe in the simplest possible way all the advantages and improvements introduced by Docker and its use; my idea was to submit it to the core team once finished, so as to support my PR with some practical content.

---

This is the current status of this project.  
I still interested in working on this project; especially if there's someone else interested.

What do you think?
Would you help me?

**Comment by mserajnik** [comment]
> The project is currently quite up to date; I haven't tried it in a while but I don't expect any major flaws... It should work as expected.

Glad to hear that!

> Since it's been a long time since the last commit, I started to notice that it would be better to add a new build tag related to the day it was built.

That sounds smart, I currently also don't tag this in my project (I only tag latest, the supported client version and the VMaNGOS commit hash).

> As you also noted, the README.md is extremely outdated (it comes from when t[here](https://github.com/Byloth/cmangos-docker/wiki/Getting-Started#using-the-cmangos-console) were no images built with GitHub Actions yet and you had to build images yourself) and the documentation is incomplete (I stopped here from writing).

What did you have in mind for the CMaNGOS console section? Probably the information how to create accounts and such? It would be good to be able to refer to official documentation, although that sadly doesn't seem to exist apart from [implicit documentation through the code](https://github.com/cmangos/mangos-tbc/blob/b36a1489df0ea5adadc9b900ffbe2d814667eb36/sql/archive/0.12/2008_10_21_02_mangos_command.sql#L8-L23). Maybe instead it would be possible to dump the whole `command` table and put all the relevant commands in a table in the wiki.

> Since the script that comes from the [original CMaNGOS project](https://github.com/cmangos/tbc-db/) isn't actually "friendly" with non-interactive use, you currently have to docker exec into the container in order to run the database CoreUpdate command.

Have you considered just patching the update script on-the-fly for the Docker images? Because it looks like this doesn't need [too many changes](https://github.com/cmangos/tbc-db/pull/1112/files) and could easily be put into a Git patch that's run when the image is built. Or is there anything speaking against that approach (other than having to sometimes maybe update the patch if the script changes)?

I would be happy to look into creating a PR for that, if that's something that would help you.

**Comment by Byloth** [comment]
> What did you have in mind for the CMaNGOS console section?

TBH, nothing more than what I wrote in [`README.md`](https://github.com/Byloth/cmangos-docker#creating-a-new-account) about...  
Only those useful for starting to use CMaNGOS; the page is named "Getting Started", after all...

Of course, perhaps by linking to some other more detailed page.  
Let's don't overload the user with too much information! 😉

---

> Have you considered just patching the update script on-the-fly for the Docker images?

Yes... I thought about it too; first I simply tried to fix the root problem before implementing a patch.  
Go on, if you want... I'll be happy. 😉

---

Right now, I'm going to add the build tag and some other minor fixes...
I'll also fix some details on the wiki! 😉

After that, let's try to be structured with our changes...  
So, let's use PRs and Issues where necessary!

I'm going to also open the "[Discussion](https://github.com/Byloth/cmangos-docker/discussions)" section, for this project.  
After that, I'll close this Issue.

In the meanwhile, let me know if you think I could do something better.
